services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rental_web
    command: /start
    volumes:
      - .:/home/app/web
    ports:
      - 8000:8000
    env_file:
      - ./.env/.prod-sample
    depends_on:
      - redis
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env/.prod.env.db

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rental_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/home/app/web
    env_file:
      - ./.env/.prod-sample
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rental_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/home/app/web
    env_file:
      - ./.env/.prod-sample
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rental_celery_flower
    command: /start-flower
    volumes:
      - .:/home/app/web
    env_file:
      - ./.env/.prod-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
