# Generated by Django 5.0.3 on 2024-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_category_options_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
