# Generated by Django 5.0.3 on 2024-03-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rental_monthly_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='has_attached_bathroom',
            field=models.BooleanField(default=False, help_text='Denotes whether bathroom is attached.'),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_bathroom_shared',
            field=models.BooleanField(default=False, help_text='Denotes whether bathroom is personal or shared with other renter.'),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_kitchen_shared',
            field=models.BooleanField(default=False, help_text='Denotes wheter the kitchen space is shared among other renters or not.'),
        ),
        migrations.AddField(
            model_name='rental',
            name='num_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='num_bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='square_footage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall dimension of property.', max_digits=10, null=True),
        ),
    ]
