# Generated by Django 5.0.3 on 2024-05-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_has_attached_bathroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
