# Generated by Django 5.0.3 on 2024-06-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_notification_created_at_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rental_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
