services:
  db:
    image: mysql:9.0.0
    container_name: db
    restart: always
    env_file:
      - .env.db
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #   - MYSQL_DATABASE=${MYSQL_DATABASE}
    #   - MYSQL_USER=${MYSQL_USER}
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./_redis_data:/var/lib/redis
      - ./redis/rc.local:/etc/rc.local

  web:
    build: .
    container_name: web
    restart: always
    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 core.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  worker:
    build: .
    container_name: worker
    restart: always
    command: celery -A core worker -l info
    healthcheck:
      test:
        - "CMD"
        - "bash"
        - "-c"
        - "celery --broker=redis://redis:6379/ inspect ping | grep OK"
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env

  beat:
    build: .
    container_name: beat
    command: celery -A core beat -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env

volumes:
  mysql_data:
